version: 2

models:
  - name: stg_taxi_trips
    columns:
      - name: trip_id
        tests:
          - unique
          - not_null

  - name: stg_taxi_zones
    columns:
      - name: location_id
        tests:
          - unique
          - not_null
